version: '3.8'  # Specify the Docker Compose version

services:
  frontend:
    build:
      context: .  # Path to your Vue.js project directory
      dockerfile: Dockerfile  # Path to your Dockerfile for the frontend
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 of the host machine
    volumes:
      - .:/app  # Mount your project directory as /app within the container

  nginx:
    image: nginx:stable-alpine  # Use the official Nginx image
    ports:
      - "80:80"  # Map port 80 of the container to port 80 of the host machine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount your Nginx configuration file

