version: '3.8' # Specify the Docker Compose version

services:
  frontend:
    build:
      context: . # Path to your Vue.js project directory
      dockerfile: Dockerfile_dev # Path to your Dockerfile for the frontend
    ports:
      - '8080:8080' # Map port 8080 of the container to port 8080 of the host machine
    volumes:
      - .:/app # Mount your project directory as /app within the container

